import React from 'react';
import {
  SiTailwindcss,
  SiRedux,
  SiStyledcomponents,
  SiSequelize,
  SiMongodb,
  SiJest,
  SiChai,
  SiTypescript,
  SiCss3,
  SiHtml5,
  SiJavascript,
  SiGnubash,
  SiVisualstudio,
} from 'react-icons/si';
import {
  GrReactjs, GrNode, GrMysql, GrDocker,
} from 'react-icons/gr';
import { DiBootstrap, DiGit, DiGithubBadge } from 'react-icons/di';
import {
  Background, ConjuntIcons, Icons, Row,
} from '../../styles';

function BackgroundAnimate() {
  return (
    <Background>
      <Row>
        <ConjuntIcons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
        </ConjuntIcons>
        <ConjuntIcons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
        </ConjuntIcons>
      </Row>
      <Row>
        <ConjuntIcons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
        </ConjuntIcons>
        <ConjuntIcons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
        </ConjuntIcons>
      </Row>
      <Row>
        <ConjuntIcons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
        </ConjuntIcons>
        <ConjuntIcons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
        </ConjuntIcons>
      </Row>
      <Row>
        <ConjuntIcons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
        </ConjuntIcons>
        <ConjuntIcons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
        </ConjuntIcons>
      </Row>
      <Row>
        <ConjuntIcons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
        </ConjuntIcons>
        <ConjuntIcons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
        </ConjuntIcons>
      </Row>
      <Row>
        <ConjuntIcons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
        </ConjuntIcons>
        <ConjuntIcons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
        </ConjuntIcons>
      </Row>
      <Row>
        <ConjuntIcons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
        </ConjuntIcons>
        <ConjuntIcons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
        </ConjuntIcons>
      </Row>
      <Row>
        <ConjuntIcons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
        </ConjuntIcons>
        <ConjuntIcons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
        </ConjuntIcons>
      </Row>
      <Row>
        <ConjuntIcons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
        </ConjuntIcons>
        <ConjuntIcons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
        </ConjuntIcons>
      </Row>
      <Row>
        <ConjuntIcons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
        </ConjuntIcons>
        <ConjuntIcons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
        </ConjuntIcons>
      </Row>
      <Row>
        <ConjuntIcons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
        </ConjuntIcons>
        <ConjuntIcons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
          <Icons><GrReactjs /></Icons>
          <Icons><DiBootstrap /></Icons>
          <Icons><SiTailwindcss /></Icons>
          <Icons><SiRedux /></Icons>
          <Icons><SiStyledcomponents /></Icons>
          <Icons><GrNode /></Icons>
          <Icons><SiSequelize /></Icons>
          <Icons><GrMysql /></Icons>
          <Icons><GrDocker /></Icons>
          <Icons><SiMongodb /></Icons>
          <Icons><SiJest /></Icons>
          <Icons><SiChai /></Icons>
          <Icons><SiTypescript /></Icons>
          <Icons><SiCss3 /></Icons>
          <Icons><SiHtml5 /></Icons>
          <Icons><SiJavascript /></Icons>
          <Icons><SiGnubash /></Icons>
          <Icons><DiGit /></Icons>
          <Icons><DiGithubBadge /></Icons>
          <Icons><SiVisualstudio /></Icons>
        </ConjuntIcons>
      </Row>
    </Background>
  );
}

export default BackgroundAnimate;
